name: franklab_python_tutorial
channels:
- defaults
- conda-forge
dependencies:
- "python>=3.6"
- numpy
- scipy
- matplotlib
- jupyter
- jupyterlab
- nb_conda
- setuptools
- pytest
- pytest-cov
- coveralls
